theme: jekyll-theme-architect
title: "Categorical Mathemagician"
description: "If you can sort it slowly, you can sort it quickly!"
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      mathjax: true